-- init.sql — Initial schema for the Zerf Digest platform.
--
-- Run against a PostgreSQL database to create all tables:
--   psql $DATABASE_URL -f apps/api/prisma/init.sql
--
-- Note: IDs are cuid() strings generated by the Prisma client at insert time.
-- Note: updatedAt is kept current by Prisma on every update — no trigger needed.

-- Digest 

CREATE TABLE "Digest" (
    "id"                  TEXT         NOT NULL PRIMARY KEY,
    "name"                TEXT         NOT NULL,

    -- Data sources
    "clickupSpaceMap"     JSONB        NOT NULL,  -- { "Project" : "space_id" }
    "slackChannelGroups"  JSONB        NOT NULL,  -- { "Project" : ["channel_id"] }

    -- Report config
    "language"            TEXT         NOT NULL DEFAULT 'es',
    "sprintOffset"        INTEGER      NOT NULL DEFAULT 0,
    "pdfEnabled"          BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Anthropic overrides (NULL = use application defaults)
    "anthropicModel"      TEXT,
    "anthropicModelSmall" TEXT,
    "autoModel"           BOOLEAN      NOT NULL DEFAULT TRUE,
    "autoModelThreshold"  INTEGER      NOT NULL DEFAULT 25,

    -- Schedule
    "scheduleEnabled"     BOOLEAN      NOT NULL DEFAULT FALSE,
    "scheduleCron"        TEXT,                   -- e.g. "0 17 * * 5"
    "scheduleTimezone"    TEXT,                   -- e.g. "America/Chicago"

    "createdAt"           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "updatedAt"           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- DigestOutput 

CREATE TABLE "DigestOutput" (
    "id"        TEXT        NOT NULL PRIMARY KEY,
    "digestId"  TEXT        NOT NULL REFERENCES "Digest"("id") ON DELETE CASCADE,

    "driver"    TEXT        NOT NULL,  -- "slack_channel" | "slack_dm" | "email" | "local_file"
    "enabled"   BOOLEAN     NOT NULL DEFAULT TRUE,
    "tone"      TEXT        NOT NULL DEFAULT 'informal',  -- "informal" | "formal"
    "format"    TEXT        NOT NULL DEFAULT 'markdown',  -- "markdown" | "html" | "json" | "plainText" | "pdf"
    "config"    JSONB       NOT NULL DEFAULT '{}',        -- driver-specific settings

    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- DigestRun 

CREATE TABLE "DigestRun" (
    "id"           TEXT        NOT NULL PRIMARY KEY,
    "digestId"     TEXT        NOT NULL REFERENCES "Digest"("id") ON DELETE CASCADE,

    "status"       TEXT        NOT NULL,  -- "pending" | "running" | "done" | "failed"
    "triggeredBy"  TEXT        NOT NULL,  -- "manual" | "schedule"

    "sprintPeriod" TEXT,                  -- e.g. "01/20 - 01/31"
    "rawDigests"   JSONB,                 -- { "informal": "...", "formal": "..." }
    "tokenUsage"   JSONB,                 -- { input, output, cacheWrite, cacheRead }
    "error"        TEXT,

    "startedAt"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "completedAt"  TIMESTAMPTZ
);

-- DigestDelivery 

CREATE TABLE "DigestDelivery" (
    "id"     TEXT        NOT NULL PRIMARY KEY,
    "runId"  TEXT        NOT NULL REFERENCES "DigestRun"("id") ON DELETE CASCADE,

    "driver" TEXT        NOT NULL,  -- which output driver handled this delivery
    "status" TEXT        NOT NULL,  -- "sent" | "failed" | "skipped"
    "error"  TEXT,

    "sentAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes 

-- Runs are always queried by digestId, ordered by startedAt
CREATE INDEX "DigestRun_digestId_startedAt_idx" ON "DigestRun" ("digestId", "startedAt" DESC);

-- Deliveries are always queried by runId
CREATE INDEX "DigestDelivery_runId_idx" ON "DigestDelivery" ("runId");

-- Outputs are always queried by digestId
CREATE INDEX "DigestOutput_digestId_idx" ON "DigestOutput" ("digestId");
