/**
 * format/types.ts — Shared types for the formatting layer.
 *
 * FormattedDigest carries the digest in every supported format.
 * TonedDigests wraps FormattedDigest per tone (informal/formal).
 * Delivery drivers pick their tone + format from TonedDigests.
 */

import type { DigestTone } from "../../config/i18n.js";

/** Text-based formats (picked via pickFormat) */
export type DigestFormat = "markdown" | "html" | "json" | "plainText";

export interface FormattedDigest {
    /** Raw markdown (as generated by Anthropic) */
    markdown: string;
    /** Styled HTML with inline CSS — ideal for email bodies */
    html: string;
    /** Structured JSON string — for programmatic consumption */
    json: string;
    /** Plain text with no formatting — universal fallback */
    plainText: string;
    /** PDF binary buffer — null if generation failed or was skipped */
    pdf: Buffer | null;
}

/**
 * All formatted variants keyed by tone.
 * Only the tones that are actually needed are generated (to save API calls).
 */
export type TonedDigests = Partial<Record<DigestTone, FormattedDigest>>;

/** Maps user-friendly aliases → DigestFormat keys (text formats only) */
const FORMAT_ALIASES: Record<string, DigestFormat> = {
    markdown: "markdown",
    md: "markdown",
    html: "html",
    json: "json",
    plaintext: "plainText",
    plain: "plainText",
    text: "plainText",
    txt: "plainText",
};

/** File extensions for each text format */
export const FORMAT_EXTENSIONS: Record<DigestFormat, string> = {
    markdown: "md",
    html: "html",
    json: "json",
    plainText: "txt",
};

/** Resolve a user-provided format string to a DigestFormat key. Returns null if invalid. */
export function resolveFormat(raw: string): DigestFormat | null {
    return FORMAT_ALIASES[raw.toLowerCase().trim()] ?? null;
}

/** Pick the text content from a FormattedDigest by format key. */
export function pickFormat(digest: FormattedDigest, format: DigestFormat): string {
    return digest[format];
}

/** Check if a format string refers to PDF (handled separately as binary) */
export function isPdfFormat(raw: string): boolean {
    return raw.toLowerCase().trim() === "pdf";
}
